### ISSUE TITLE
大漠

### ISSUE THREAD

**Issue by Hwangss** [css-conf/2#10]
理由：w3cplus站长，致力于推广CSS3等高新技术，sass布道者，许多前端的启蒙导师。
想听话题：sass工程化、移动端的CSS走势、未来的CSS世界
博客：http://www.w3cplus.com/

**Comment by ddian** [comment]
赞！

**Comment by Honey-Monkey** [comment]
赞!

**Comment by lishengzxc** [comment]
:thumbsup:

**Comment by dudy5** [comment]
+1

**Comment by xjiujiu** [comment]
+1

**Comment by yeyuguo** [comment]
的确应该赞，很多好的css的东西都能看到他的身影

**Comment by ifci** [comment]
+1

**Comment by ideazhao** [comment]
+1

**Comment by ellyliang** [comment]
支持，看到大漠微信上推的有关css的知识都很新

**Comment by yisibl** [comment]
好想抱大腿！

**Comment by airen** [comment]
我一直抱着楼上姐姐的大腿不放。谢谢大家推荐，国语说出来没人听得懂，说洋文又说不出来，所以上不了台面，只能在台下围观各位大大。

**Comment by wnow20** [comment]
能不能讲一些基础的，追求实际一点的？ 比如：
- CSS模块化思想（命名规范等）
- CSS设计模式，优化CSS层叠机制
- Less/Sass模块化最佳实践
- CSS底层原理
- 不知道怎么说，平时写 css 的时候写复杂了，经常存在不确定性，大神能不能给我们指明方向。让我改变思维增强CSS编程的确定性
