### ISSUE TITLE
贺师俊 johnhax

### ISSUE THREAD

**Issue by zhouzhongyuan** [css-conf/2#11]
<li>推荐理由 ：前端大牛，干货多</li>
<li>想听什么的话题： <b>电子书排版 ，横排 epub实现</b></li>
<li>推荐人的 GitHub / 博客 / 微博 等地址 <a href="http://johnhax.net/">http://johnhax.net/</a></li>

**Comment by lishengzxc** [comment]
+1

**Comment by dudy5** [comment]
国内最懂web标准的大师。+1

**Comment by yisibl** [comment]
+1 好想当面膜拜！

**Comment by ideazhao** [comment]
+1

**Comment by cssmagic** [comment]
贺老要筹备今年 QCon 上海站的前端板块，估计分不出精力了。遗憾。
