### ISSUE TITLE
FuryBean

### ISSUE THREAD

**Issue by zhouzhongyuan** [css-conf/2#12]
<li>推荐理由 ：听说是一个40分钟可以写一个框架的男人</li>
<li>想听什么的话题： <b>如何在40分钟写一个mvvm框架，详细的！！！</b></li>
<li>推荐人的 GitHub / 博客 / 微博 等地址 <a href="http://weibo.com/jsfan">微博FuryBean</a></li>

**Comment by lishengzxc** [comment]
+1

**Comment by dudy5** [comment]
虽然我不了解，但我觉得还是可以+1的
