### ISSUE TITLE
css魔法哥

### ISSUE THREAD

**Issue by jianjiade** [css-conf/2#13]
css的conf当然要让css魔法哥上台了，谁让他微博ID是<code>CSS魔法</code>的呢？<br>
[css魔法微博](http://weibo.com/cssmagic)<br>
[css魔法哥博客](https://github.com/cssmagic/blog/issues)<br>
<img src="http://tp3.sinaimg.cn/1645021302/180/5666354144/1" />

**Comment by dudy5** [comment]
顶魔法哥。+1

**Comment by ideazhao** [comment]
+1

**Comment by yisibl** [comment]
必须的！

**Comment by jianjiade** [comment]
我推荐的，确认参加，第一届推荐的 点头猪，也确认参加，O(∩_∩)O哈哈~

**Comment by cssmagic** [comment]
谢谢各位支持！谢谢贺老 (@hax) 的推荐和鼓励！
