### ISSUE TITLE
阿当#14

### ISSUE THREAD

**Issue by ghost** [css-conf/2#14]
<ul>
<li>推荐理由：web前端开发修炼之道作者</li>
<li>想听什么的话题：web组件开发</li>
<li>推荐人的 GitHub / 博客 / 微博 等地址：<a href="http://weibo.com/u/1659574154/">真阿当</a></li>
</ul>

**Comment by Hwangss** [comment]
顶当哥，启蒙导师

**Comment by ideazhao** [comment]
+1

**Comment by dudy5** [comment]
+1
