### ISSUE TITLE
Eric Meyer

### ISSUE THREAD

**Issue by ideazhao** [css-conf/2#15]
最负盛名的世界级HTML和css专家，w3c css&FP工作组成员，WaC CSS测试套件的负责人。《Smashing CSS》(即《精彩绝伦的css》), 《CSS: The Definitive Guide》（即《css权威指南》）, 《CSS Pocket Reference, and Cascading Style Sheets 2.0 Programmer’s Reference》等书的作者。还有一系列著名网络教程。
不知能否邀请他过来呢？~

**Comment by yisibl** [comment]
+1

**Comment by xiaoqiang730730** [comment]
+1

**Comment by ericlva** [comment]
+1

**Comment by cssmagic** [comment]
我的网名来自于 Meyer 老师的《Eric Meyer on CSS》一书。
