### ISSUE TITLE
otakustay

### ISSUE THREAD

**Issue by DualWield** [css-conf/2#16]
艾特不了本人不知道为什么。。。。
https://github.com/otakustay

**Comment by itchina110** [comment]
想听灰大讲什么

**Comment by ghost** [comment]
@otakustay

**Comment by DualWield** [comment]
browser's rendering engine about css.
i.e.Parsing HTML to construct the DOM tree -> Render tree construction -> layout of the render tree -> painting the render tree

**Comment by otakustay** [comment]
感谢各位的推荐，不过我并不清楚是否适合在这种尖端的交流会上讲如此基础的东西……

另外我也推荐 @Justineo 同学，基本上我能说的没有他不行的了
