### ISSUE TITLE
张克军

### ISSUE THREAD

**Issue by lishengzxc** [css-conf/2#4]
推荐理由：前端老兵，产品工程师，演讲台风也超自然。
想听什么的话题：前端工程化
个人博客地址：[http://hikejun.com/blog/](http://hikejun.com/blog/)

**Comment by yisibl** [comment]
+1

**Comment by ideazhao** [comment]
为什么来顶的人不多呢，了解的不多么？+1

**Comment by ericlva** [comment]
yisi 姐姐 +1
