### ISSUE TITLE
拴萝卜的棍子

### ISSUE THREAD

**Issue by hax** [css-conf/2#6]
上次没来，这次来吧 https://github.com/css-conf/1/issues/35
@leeluolee

**Comment by yisibl** [comment]
+1

**Comment by leeluolee** [comment]
多谢 @hax 还记得去年无耻自荐的我 。

最近一年对css没有太深入的思考， 我能想到的Topic有:
1. 还是css预处理技术，这个去年已经介绍过了 https://github.com/css-conf/1/issues/35。 
2. 最近整理过[一些clip-path的东西](http://www.w3cplus.com/svg/species-in-pieces.html)

如果对哪一个感兴趣，我非常乐意来做个分享。

不过无论上不上台，这次都会去参会，毕竟上海近， 顺便去围观下css领域的大神们。

**Comment by yisibl** [comment]
@leeluolee 最近有看看 PostCSS 吗？

**Comment by rchee** [comment]
+1，想听预处理技术的深入讨论~网上能看到的教程基本都还停留在入门的阶段

**Comment by leeluolee** [comment]
@yisibl  后处理器与预处理器最大的区别就是输入的是标准css(至少从语法上)和自建DSL

### 能力上: 预处理器是包含后处理器的能力的

其实预处理器应该都会有标准css语法树的生成的输出, 同时也都接受标准css输入.  其流程一般是

```
xcss --(词法+语法解析)--> AST(自建DSL)  --(解释器)-->  AST(CSS) -- (翻译器 ) -> css输出。
```

如果我们在解释器游历AST（自建DSL）的上升阶段预留 hook（或直接操作输出的AST:css）就可以实现postcss的能力。比如 https://github.com/leeluolee/mcss#作为css-parser-的mcss 和使用hook实现的[csscss冗余工具DEMO](https://github.com/leeluolee/mcss/issues/3)，一些独立的工具借由这些输出的AST是很容易实现的

### 表达能力上: 后处理器弱于预处理器，但是可读性强于预处理器

由于nest ruleset/media 等我们常用的预处理器的common feature 并不是合法的css 语法规则， 有些东西确实是双刃剑，但是nested ruleset 在经过适当普及之后是  100%的利大于弊.  。  再比如变量， 在我12-13年关注这个领域时， variable这个相关的规范变化非常不稳定， 我不知道目前稳定了没有。但是无论如何在标准css语法上扩展的变量定义肯定没有

``` scss
$border-width = 20px;
$reset-rule ?= true;
```

这样的方式来的更加的直观，虽然引入了一般编程语言的东西。

如果标准css的写法足以解决工程里的问题，配以合适的插件， 那选择postcss当然没有问题。

### 现在预处理器越来越后， 后处理器越来越前， 两者其实没有对立关系。

**Comment by Justineo** [comment]
给你们看看这个<ruby>讨<rp>(</rp><rt>sī</rt><rp>)</rp>论<rp>(</rp><rt>bī</rt><rp>)</rp></ruby>：https://github.com/postcss/postcss/issues/320

**Comment by yisibl** [comment]
@Justineo 两个字 「作」！

**Comment by yisibl** [comment]
@Justineo 两个字 「作」！

**Comment by yisibl** [comment]
@Justineo 两个字 「作」！

**Comment by yisibl** [comment]
@Justineo 两个字 「作」！

**Comment by yisibl** [comment]
@Justineo 两个字 「作」！

**Comment by sofish** [comment]
@leeluolee 来讲讲吗？

**Comment by leeluolee** [comment]
@sofish OK 。
