### ISSUE TITLE
Andrey Sitnik

### ISSUE THREAD

**Issue by yisibl** [css-conf/2#8]
@ai https://github.com/ai

[PostCSS](https://github.com/postcss/postcss)，[Autoprefixer](https://github.com/postcss/autoprefixer) 等工具作者，对 CSS 预处理器有深入的实践，希望听听他对整个未来 CSS 开发模式的规划。

**Comment by dudy5** [comment]
+1

**Comment by ideazhao** [comment]
+1

**Comment by cssmagic** [comment]
+1 有兴趣！
